export const MEMORY_TIMEOUT_SETTING = 1000;

export const MEMORY_CARD_SETS = {
  VERSION_WITH_8_CARDS: [
    { id: 1, name: "Pies", image: "images/pies.jpg", isGuess: false },
    { id: 1, name: "Pies", image: "images/pies.jpg", isGuess: false },
    { id: 2, name: "Szop", image: "images/szop.jpg", isGuess: false },
    { id: 2, name: "Szop", image: "images/szop.jpg", isGuess: false },
    { id: 3, name: "Żyrafa", image: "images/zyrafa.jpg", isGuess: false },
    { id: 3, name: "Żyrafa", image: "images/zyrafa.jpg", isGuess: false },
    { id: 4, name: "Słoń", image: "images/slon.jpg", isGuess: false },
    { id: 4, name: "Słoń", image: "images/slon.jpg", isGuess: false },
  ],

  VERSION_WITH_12_CARDS: [
    { id: 1, name: "Pies", image: "images/pies.jpg", isGuess: false },
    { id: 1, name: "Pies", image: "images/pies.jpg", isGuess: false },
    { id: 2, name: "Szop", image: "images/szop.jpg", isGuess: false },
    { id: 2, name: "Szop", image: "images/szop.jpg", isGuess: false },
    { id: 3, name: "Żyrafa", image: "images/zyrafa.jpg", isGuess: false },
    { id: 3, name: "Żyrafa", image: "images/zyrafa.jpg", isGuess: false },
    { id: 4, name: "Słoń", image: "images/slon.jpg", isGuess: false },
    { id: 4, name: "Słoń", image: "images/slon.jpg", isGuess: false },
    { id: 5, name: "Małpa", image: "images/malpa.jpg", isGuess: false },
    { id: 5, name: "Małpa", image: "images/malpa.jpg", isGuess: false },
    { id: 6, name: "Koń", image: "images/kon.jpg", isGuess: false },
    { id: 6, name: "Koń", image: "images/kon.jpg", isGuess: false },
  ],
  VERSION_WITH_16_CARDS: [
    { id: 1, name: "Pies", image: "images/pies.jpg", isGuess: false },
    { id: 1, name: "Pies", image: "images/pies.jpg", isGuess: false },
    { id: 2, name: "Szop", image: "images/szop.jpg", isGuess: false },
    { id: 2, name: "Szop", image: "images/szop.jpg", isGuess: false },
    { id: 3, name: "Żyrafa", image: "images/zyrafa.jpg", isGuess: false },
    { id: 3, name: "Żyrafa", image: "images/zyrafa.jpg", isGuess: false },
    { id: 4, name: "Słoń", image: "images/slon.jpg", isGuess: false },
    { id: 4, name: "Słoń", image: "images/slon.jpg", isGuess: false },
    { id: 5, name: "Małpa", image: "images/malpa.jpg", isGuess: false },
    { id: 5, name: "Małpa", image: "images/malpa.jpg", isGuess: false },
    { id: 6, name: "Koń", image: "images/kon.jpg", isGuess: false },
    { id: 6, name: "Koń", image: "images/kon.jpg", isGuess: false },
    { id: 7, name: "Papuga", image: "images/papuga.jpg", isGuess: false },
    { id: 7, name: "Papuga", image: "images/papuga.jpg", isGuess: false },
    { id: 8, name: "Żuk", image: "images/zuk.jpg", isGuess: false },
    { id: 8, name: "Żuk", image: "images/zuk.jpg", isGuess: false },
  ],
};
