export const MEMORY_TIMEOUT_SETTING = 1000;

export const MEMORY_CARD_SETS = {
  VERSION_WITH_8_CARDS: [ { id: 1, name: "Pies", image: "", isGuess: false },
  { id: 1, name: "Pies", image: "", isGuess: false },
  { id: 2, name: "Kot", image: "", isGuess: false },
  { id: 2, name: "Kot", image: "", isGuess: false },
  { id: 3, name: "Żyrafa", image: "", isGuess: false },
  { id: 3, name: "Żyrafa", image: "", isGuess: false },
  { id: 4, name: "Słoń", image: "", isGuess: false },
  { id: 4, name: "Słoń", image: "", isGuess: false },],
  VERSION_WITH_12_CARDS: [ { id: 1, name: "Pies", image: "", isGuess: false },
  { id: 1, name: "Pies", image: "", isGuess: false },
  { id: 2, name: "Kot", image: "", isGuess: false },
  { id: 2, name: "Kot", image: "", isGuess: false },
  { id: 3, name: "Żyrafa", image: "", isGuess: false },
  { id: 3, name: "Żyrafa", image: "", isGuess: false },
  { id: 4, name: "Słoń", image: "", isGuess: false },
  { id: 4, name: "Słoń", image: "", isGuess: false },
  { id: 5, name: "Małpa", image: "", isGuess: false },
  { id: 5, name: "Małpa", image: "", isGuess: false },
  { id: 6, name: "Koń", image: "", isGuess: false },
  { id: 6, name: "Koń", image: "", isGuess: false },
],
VERSION_WITH_24_CARDS: [ { id: 1, name: "Pies", image: "", isGuess: false },
  { id: 1, name: "Pies", image: "", isGuess: false },
  { id: 2, name: "Szop", image: "", isGuess: false },
  { id: 2, name: "Szop", image: "", isGuess: false },
  { id: 3, name: "Żyrafa", image: "", isGuess: false },
  { id: 3, name: "Żyrafa", image: "", isGuess: false },
  { id: 4, name: "Słoń", image: "", isGuess: false },
  { id: 4, name: "Słoń", image: "", isGuess: false },
  { id: 5, name: "Małpa", image: "", isGuess: false },
  { id: 5, name: "Małpa", image: "", isGuess: false },
  { id: 6, name: "Koń", image: "", isGuess: false },
  { id: 6, name: "Koń", image: "", isGuess: false },
  { id: 7, name: "Papuga", image: "", isGuess: false },
  { id: 7, name: "Papuga", image: "", isGuess: false },
  { id: 8, name: "Borsuk", image: "", isGuess: false },
  { id: 8, name: "Borsuk", image: "", isGuess: false },
  { id: 9, name: "Wilk", image: "", isGuess: false },
  { id: 9, name: "Wilk", image: "", isGuess: false },
  { id: 10, name: "Tygrys", image: "", isGuess: false },
  { id: 10, name: "Tygrys", image: "", isGuess: false },
  { id: 11, name: "Żuk", image: "", isGuess: false },
  { id: 11, name: "Żuk", image: "", isGuess: false },
  { id: 12, name: "Leniwiec", image: "", isGuess: false },
  { id: 12, name: "Leniwiec", image: "", isGuess: false },

]
}